import { AccountId, Balance, ChannelId, PreImage, Moment, Hash, Public, TicketEpoch } from './base';
import { ChannelBalance, Channel, Funded, Active, PendingSettlement } from './channel';
import { State } from './state';
import { Ticket } from './ticket';
import { Signature } from './signature';
import { SignedTicket } from './signedTicket';
import { SignedChannel } from './signedChannel';
declare const SRMLTypes: {
    AccountId: typeof AccountId;
    Balance: typeof Balance;
    ChannelId: typeof ChannelId;
    PreImage: typeof PreImage;
    Moment: typeof Moment;
    Hash: typeof Hash;
    Public: typeof Public;
    ChannelBalance: typeof ChannelBalance;
    Channel: typeof Channel;
    Funded: typeof Funded;
    State: typeof State;
    Ticket: typeof Ticket;
    TicketEpoch: typeof TicketEpoch;
};
declare const Types: {
    AccountId: typeof AccountId;
    Balance: typeof Balance;
    ChannelId: typeof ChannelId;
    PreImage: typeof PreImage;
    Moment: typeof Moment;
    Hash: typeof Hash;
    Public: typeof Public;
    ChannelBalance: typeof ChannelBalance;
    Channel: typeof Channel;
    Funded: typeof Funded;
    State: typeof State;
    Ticket: typeof Ticket;
    TicketEpoch: typeof TicketEpoch;
    NativeBalance: typeof Balance;
    SignedChannel: typeof SignedChannel;
    SignedTicket: typeof SignedTicket;
    Signature: typeof Signature;
};
export { SRMLTypes, Types, SignedChannel, SignedTicket, Signature, AccountId, Balance, Balance as NativeBalance, ChannelId, PreImage, Moment, Hash, Public, ChannelBalance, Channel, Active, Funded, PendingSettlement, Ticket, State, };
